version: '3.9'
services:
  backend:
    container_name: backend
    image: auth-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: auth
      DB_USERNAME: app
      DB_PASSWORD: pass
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    volumes:
      - .dbdata:/var/lib/mysql
